2025-01-01 16:01:00 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:01:00 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:01:00 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:04:11 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:04:11 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:04:11 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:19:36 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:19:36 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:19:38 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:23:28 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:23:28 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:23:28 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: analyse_tree() missing 1 required positional argument: 'file_path'
2025-01-01 16:24:26 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:24:26 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:24:28 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:26:49 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:26:49 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:26:51 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:30:06 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:30:06 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:30:08 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:31:37 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:31:37 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:31:40 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:52:29 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:52:29 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:52:31 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:53:36 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:53:36 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:53:38 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:54:40 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:54:40 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:54:42 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:55:01 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:55:01 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:55:03 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:56:36 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:56:36 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:56:38 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:58:45 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 16:58:45 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 16:58:48 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:01:35 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:01:35 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:01:37 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:04:23 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:04:23 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:04:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:05:01 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:05:01 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:05:03 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:06:21 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:06:21 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:06:23 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:07:23 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:07:23 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:07:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:07:52 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:07:52 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:07:54 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:08:08 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:08:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:08:09 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:10:20 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:10:20 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:10:22 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:13:22 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:13:22 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:13:24 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:13:40 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:13:40 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:13:42 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:14:34 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:14:34 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:14:35 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:17:57 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-01 17:17:57 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-01 17:17:59 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 05:48:34 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 05:48:34 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 05:48:34 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 05:48:43 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 05:48:43 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 05:48:43 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 05:50:23 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 05:50:23 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 05:50:23 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 05:54:17 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 05:54:17 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 05:54:17 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:04:55 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 06:04:55 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:04:55 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:11:44 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 06:11:44 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:11:48 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:14:34 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 06:14:34 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:14:34 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'coroutine' object has no attribute 'splitlines'
2025-01-02 06:16:00 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 06:16:00 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:16:00 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:20:18 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 06:20:18 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:20:22 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:21:07 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 06:21:07 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:21:11 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:22:12 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 06:22:12 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 06:22:16 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:27:24 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:27:24 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:27:28 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:27:58 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:27:58 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:28:02 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:28:37 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:28:37 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:28:41 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:31:04 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:31:04 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:31:08 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:34:43 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:34:43 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:34:48 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:36:05 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:36:05 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:36:09 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:36:22 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:36:22 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:36:26 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:42:48 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:42:48 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:42:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:44:43 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:44:43 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:44:47 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:57:37 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:57:37 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:57:41 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:59:09 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 10:59:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 10:59:13 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:01:03 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:01:03 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:01:08 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:03:09 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:03:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:03:13 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:04:09 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:04:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:04:14 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:04:48 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:04:48 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:04:52 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:05:20 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:05:20 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:05:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:05:56 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:05:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:06:00 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:09:06 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:09:06 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:09:11 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:11:08 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:11:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:11:10 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:12:35 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:12:35 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:12:37 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:14:05 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:14:05 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:14:07 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:17:23 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:17:23 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:17:26 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:20:42 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:20:42 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:20:45 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:21:03 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:21:03 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:21:05 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:22:30 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:22:30 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:22:32 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:23:12 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:23:12 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:23:15 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:23:51 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:23:51 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:23:54 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:25:13 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:25:13 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:25:16 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:26:24 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:26:24 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:26:26 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:26:31 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:26:31 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:26:34 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:27:06 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:27:06 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:27:09 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:30:43 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:30:43 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:30:46 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:31:07 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:31:07 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:31:09 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:47:50 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:47:50 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:47:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:48:22 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:48:22 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:48:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:50:24 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\Doc-Man-r1
2025-01-02 11:50:24 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\config.py
2025-01-02 11:50:24 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\config.py
2025-01-02 11:50:24 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\main.py
2025-01-02 11:50:26 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\main.py
2025-01-02 11:50:26 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\output.py
2025-01-02 11:50:28 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\output.py
2025-01-02 11:50:28 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google_auth_httplib2.py
2025-01-02 11:50:30 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google_auth_httplib2.py
2025-01-02 11:50:30 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\typing_extensions.py
2025-01-02 11:50:32 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\typing_extensions.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:50:32 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\_virtualenv.py
2025-01-02 11:50:35 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\_virtualenv.py
2025-01-02 11:50:35 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\annotated_types\test_cases.py
2025-01-02 11:50:35 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\annotated_types\test_cases.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:50:35 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\annotated_types\__init__.py
2025-01-02 11:50:40 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\annotated_types\__init__.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:50:40 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\apiclient\__init__.py
2025-01-02 11:50:40 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\apiclient\__init__.py
2025-01-02 11:50:40 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\cachetools\func.py
2025-01-02 11:50:42 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\cachetools\func.py
2025-01-02 11:50:42 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\cachetools\keys.py
2025-01-02 11:50:43 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\cachetools\keys.py
2025-01-02 11:50:43 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\cachetools\__init__.py
2025-01-02 11:50:53 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\cachetools\__init__.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:50:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\certifi\core.py
2025-01-02 11:50:56 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\certifi\core.py
2025-01-02 11:50:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\certifi\__init__.py
2025-01-02 11:50:56 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\certifi\__init__.py
2025-01-02 11:50:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\certifi\__main__.py
2025-01-02 11:50:56 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\certifi\__main__.py
2025-01-02 11:50:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\api.py
2025-01-02 11:50:56 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\api.py
2025-01-02 11:50:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\cd.py
2025-01-02 11:50:56 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\cd.py
2025-01-02 11:50:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\constant.py
2025-01-02 11:50:56 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\constant.py: 'charmap' codec can't encode character '\u0142' in position 23747: character maps to <undefined>
2025-01-02 11:50:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\legacy.py
2025-01-02 11:50:56 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\legacy.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:50:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\md.py
2025-01-02 11:51:02 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\md.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:51:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\models.py
2025-01-02 11:51:10 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\models.py
2025-01-02 11:51:10 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\utils.py
2025-01-02 11:51:16 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\utils.py: 'charmap' codec can't encode character '\uff5c' in position 3374: character maps to <undefined>
2025-01-02 11:51:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\version.py
2025-01-02 11:51:16 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\version.py
2025-01-02 11:51:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\__init__.py
2025-01-02 11:51:16 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\__init__.py: 'charmap' codec can't encode characters in position 439-442: character maps to <undefined>
2025-01-02 11:51:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\__main__.py
2025-01-02 11:51:16 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\__main__.py
2025-01-02 11:51:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\cli\__init__.py
2025-01-02 11:51:16 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\cli\__init__.py
2025-01-02 11:51:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\cli\__main__.py
2025-01-02 11:51:16 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\charset_normalizer\cli\__main__.py
2025-01-02 11:51:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\ansi.py
2025-01-02 11:51:19 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\ansi.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:51:19 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\ansitowin32.py
2025-01-02 11:51:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\ansitowin32.py
2025-01-02 11:51:25 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\initialise.py
2025-01-02 11:51:27 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\initialise.py
2025-01-02 11:51:27 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\win32.py
2025-01-02 11:51:30 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\win32.py
2025-01-02 11:51:30 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\winterm.py
2025-01-02 11:51:30 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\winterm.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:51:30 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\__init__.py
2025-01-02 11:51:30 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\__init__.py
2025-01-02 11:51:30 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\ansitowin32_test.py
2025-01-02 11:51:38 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\ansitowin32_test.py
2025-01-02 11:51:38 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\ansi_test.py
2025-01-02 11:51:39 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\ansi_test.py
2025-01-02 11:51:39 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\initialise_test.py
2025-01-02 11:51:45 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\initialise_test.py
2025-01-02 11:51:45 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\isatty_test.py
2025-01-02 11:51:47 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\isatty_test.py
2025-01-02 11:51:47 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\utils.py
2025-01-02 11:51:49 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\utils.py
2025-01-02 11:51:49 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\winterm_test.py
2025-01-02 11:51:51 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\winterm_test.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:51:51 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\__init__.py
2025-01-02 11:51:51 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\colorama\tests\__init__.py
2025-01-02 11:51:51 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\cli.py
2025-01-02 11:51:51 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\cli.py
2025-01-02 11:51:51 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\ipython.py
2025-01-02 11:51:51 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\ipython.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:51:51 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\main.py
2025-01-02 11:51:52 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\main.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:51:52 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\parser.py
2025-01-02 11:51:52 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\parser.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:51:52 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\variables.py
2025-01-02 11:51:53 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\variables.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:51:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\version.py
2025-01-02 11:51:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\version.py
2025-01-02 11:51:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\__init__.py
2025-01-02 11:51:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\__init__.py
2025-01-02 11:51:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\__main__.py
2025-01-02 11:51:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\dotenv\__main__.py
2025-01-02 11:51:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage\gapic_version.py
2025-01-02 11:51:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage\gapic_version.py
2025-01-02 11:51:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage\__init__.py
2025-01-02 11:51:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage\__init__.py
2025-01-02 11:51:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\gapic_version.py
2025-01-02 11:51:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\gapic_version.py
2025-01-02 11:51:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\__init__.py
2025-01-02 11:51:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\__init__.py
2025-01-02 11:51:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\__init__.py
2025-01-02 11:51:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\__init__.py
2025-01-02 11:51:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\async_client.py
2025-01-02 11:51:54 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\async_client.py
2025-01-02 11:51:54 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\client.py
2025-01-02 11:51:55 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\client.py
2025-01-02 11:51:55 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\__init__.py
2025-01-02 11:51:55 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\__init__.py
2025-01-02 11:51:55 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\base.py
2025-01-02 11:51:56 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\base.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:51:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\grpc.py
2025-01-02 11:51:56 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\grpc.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:51:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\grpc_asyncio.py
2025-01-02 11:51:57 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\grpc_asyncio.py
2025-01-02 11:51:57 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\rest.py
2025-01-02 11:51:57 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\rest.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:51:57 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\__init__.py
2025-01-02 11:51:57 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\generative_service\transports\__init__.py
2025-01-02 11:51:57 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\async_client.py
2025-01-02 11:51:58 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\async_client.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:51:58 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\client.py
2025-01-02 11:51:59 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\client.py
2025-01-02 11:51:59 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\pagers.py
2025-01-02 11:51:59 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\pagers.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:51:59 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\__init__.py
2025-01-02 11:51:59 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\__init__.py
2025-01-02 11:51:59 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\base.py
2025-01-02 11:52:00 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\base.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:52:00 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\grpc.py
2025-01-02 11:52:01 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\grpc.py
2025-01-02 11:52:01 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\grpc_asyncio.py
2025-01-02 11:52:02 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\grpc_asyncio.py
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\rest.py
2025-01-02 11:52:02 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\rest.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\__init__.py
2025-01-02 11:52:02 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\services\model_service\transports\__init__.py
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\citation.py
2025-01-02 11:52:02 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\citation.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\content.py
2025-01-02 11:52:02 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\content.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\generative_service.py
2025-01-02 11:52:02 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\generative_service.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\model.py
2025-01-02 11:52:02 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\model.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\model_service.py
2025-01-02 11:52:02 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\model_service.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\safety.py
2025-01-02 11:52:02 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\safety.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\__init__.py
2025-01-02 11:52:02 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1\types\__init__.py
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\gapic_version.py
2025-01-02 11:52:02 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\gapic_version.py
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\__init__.py
2025-01-02 11:52:02 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\__init__.py
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\__init__.py
2025-01-02 11:52:02 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\__init__.py
2025-01-02 11:52:02 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\async_client.py
2025-01-02 11:52:03 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\async_client.py
2025-01-02 11:52:03 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\client.py
2025-01-02 11:52:03 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\client.py
2025-01-02 11:52:03 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\pagers.py
2025-01-02 11:52:05 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\pagers.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:52:05 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\__init__.py
2025-01-02 11:52:05 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\__init__.py
2025-01-02 11:52:05 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\base.py
2025-01-02 11:52:06 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\base.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:52:06 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\grpc.py
2025-01-02 11:52:06 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\grpc.py
2025-01-02 11:52:06 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\grpc_asyncio.py
2025-01-02 11:52:07 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\grpc_asyncio.py
2025-01-02 11:52:07 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\rest.py
2025-01-02 11:52:07 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\rest.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:07 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\__init__.py
2025-01-02 11:52:07 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\cache_service\transports\__init__.py
2025-01-02 11:52:07 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\async_client.py
2025-01-02 11:52:07 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\async_client.py
2025-01-02 11:52:07 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\client.py
2025-01-02 11:52:08 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\client.py
2025-01-02 11:52:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\__init__.py
2025-01-02 11:52:08 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\__init__.py
2025-01-02 11:52:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\base.py
2025-01-02 11:52:08 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\base.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:52:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\grpc.py
2025-01-02 11:52:09 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\grpc.py
2025-01-02 11:52:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\grpc_asyncio.py
2025-01-02 11:52:09 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\grpc_asyncio.py
2025-01-02 11:52:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\rest.py
2025-01-02 11:52:09 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\rest.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\__init__.py
2025-01-02 11:52:09 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\discuss_service\transports\__init__.py
2025-01-02 11:52:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\async_client.py
2025-01-02 11:52:10 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\async_client.py
2025-01-02 11:52:10 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\client.py
2025-01-02 11:52:10 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\client.py
2025-01-02 11:52:10 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\pagers.py
2025-01-02 11:52:13 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\pagers.py
2025-01-02 11:52:13 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\__init__.py
2025-01-02 11:52:13 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\__init__.py
2025-01-02 11:52:13 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\base.py
2025-01-02 11:52:14 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\base.py
2025-01-02 11:52:14 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\grpc.py
2025-01-02 11:52:15 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\grpc.py
2025-01-02 11:52:15 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\grpc_asyncio.py
2025-01-02 11:52:15 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\grpc_asyncio.py
2025-01-02 11:52:15 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\rest.py
2025-01-02 11:52:15 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\rest.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:15 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\__init__.py
2025-01-02 11:52:15 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\file_service\transports\__init__.py
2025-01-02 11:52:15 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\async_client.py
2025-01-02 11:52:16 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\async_client.py
2025-01-02 11:52:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\client.py
2025-01-02 11:52:16 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\client.py
2025-01-02 11:52:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\__init__.py
2025-01-02 11:52:16 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\__init__.py
2025-01-02 11:52:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\base.py
2025-01-02 11:52:19 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\base.py
2025-01-02 11:52:19 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\grpc.py
2025-01-02 11:52:19 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\grpc.py
2025-01-02 11:52:19 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\grpc_asyncio.py
2025-01-02 11:52:19 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\grpc_asyncio.py
2025-01-02 11:52:19 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\rest.py
2025-01-02 11:52:19 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\rest.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:19 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\__init__.py
2025-01-02 11:52:19 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\transports\__init__.py
2025-01-02 11:52:19 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\async_client.py
2025-01-02 11:52:20 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\async_client.py
2025-01-02 11:52:20 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\client.py
2025-01-02 11:52:20 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\client.py
2025-01-02 11:52:20 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\pagers.py
2025-01-02 11:52:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\pagers.py
2025-01-02 11:52:25 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\__init__.py
2025-01-02 11:52:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\__init__.py
2025-01-02 11:52:25 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\base.py
2025-01-02 11:52:28 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\base.py
2025-01-02 11:52:28 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\grpc.py
2025-01-02 11:52:29 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\grpc.py
2025-01-02 11:52:29 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\grpc_asyncio.py
2025-01-02 11:52:29 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\grpc_asyncio.py
2025-01-02 11:52:29 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\rest.py
2025-01-02 11:52:29 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\rest.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:29 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\__init__.py
2025-01-02 11:52:29 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\model_service\transports\__init__.py
2025-01-02 11:52:29 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\async_client.py
2025-01-02 11:52:30 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\async_client.py
2025-01-02 11:52:30 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\client.py
2025-01-02 11:52:30 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\client.py
2025-01-02 11:52:30 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\pagers.py
2025-01-02 11:52:32 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\pagers.py
2025-01-02 11:52:32 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\__init__.py
2025-01-02 11:52:32 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\__init__.py
2025-01-02 11:52:32 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\base.py
2025-01-02 11:52:35 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\base.py
2025-01-02 11:52:35 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\grpc.py
2025-01-02 11:52:35 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\grpc.py
2025-01-02 11:52:35 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\grpc_asyncio.py
2025-01-02 11:52:36 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\grpc_asyncio.py
2025-01-02 11:52:36 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\rest.py
2025-01-02 11:52:36 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\rest.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:36 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\__init__.py
2025-01-02 11:52:36 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\permission_service\transports\__init__.py
2025-01-02 11:52:36 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\async_client.py
2025-01-02 11:52:36 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\async_client.py
2025-01-02 11:52:36 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\client.py
2025-01-02 11:52:37 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\client.py
2025-01-02 11:52:37 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\__init__.py
2025-01-02 11:52:37 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\__init__.py
2025-01-02 11:52:37 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\base.py
2025-01-02 11:52:38 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\base.py
2025-01-02 11:52:38 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\grpc.py
2025-01-02 11:52:38 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\grpc.py
2025-01-02 11:52:38 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\grpc_asyncio.py
2025-01-02 11:52:39 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\grpc_asyncio.py
2025-01-02 11:52:39 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\rest.py
2025-01-02 11:52:39 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\rest.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:39 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\__init__.py
2025-01-02 11:52:39 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\prediction_service\transports\__init__.py
2025-01-02 11:52:39 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\retriever_service\async_client.py
2025-01-02 11:52:39 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\retriever_service\async_client.py
2025-01-02 11:52:39 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\retriever_service\client.py
2025-01-02 11:52:40 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\retriever_service\client.py
2025-01-02 11:52:40 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\retriever_service\pagers.py
2025-01-02 11:52:47 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\retriever_service\pagers.py
2025-01-02 11:52:47 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\retriever_service\__init__.py
2025-01-02 11:52:47 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\retriever_service\__init__.py
2025-01-02 11:52:47 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\Doc-Man-r1\.venv\Lib\site-packages\google\ai\generativelanguage_v1beta\services\retriever_service\transports\base.py
2025-01-02 11:52:54 - file_reader - INFO - Processing directory: core
2025-01-02 11:52:54 - file_reader - INFO - Processing file: core\analysis.py
2025-01-02 11:52:56 - file_reader - ERROR - An exception occurred while processing core\analysis.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:52:56 - file_reader - INFO - Processing file: core\docman.py
2025-01-02 11:53:00 - file_reader - ERROR - An exception occurred while processing core\docman.py: 'NoneType' object has no attribute 'splitlines'
2025-01-02 11:53:00 - file_reader - INFO - Processing file: core\queries.py
2025-01-02 11:53:00 - file_reader - INFO - Successfully processed file: core\queries.py
2025-01-02 11:53:00 - file_reader - INFO - Processing file: core\generator\docstringGenarator.py
2025-01-02 11:53:01 - file_reader - INFO - Successfully processed file: core\generator\docstringGenarator.py
2025-01-02 11:53:01 - file_reader - INFO - Processing file: core\treeSitter\treeSitterConfig.py
2025-01-02 11:53:01 - file_reader - INFO - Successfully processed file: core\treeSitter\treeSitterConfig.py
2025-01-02 11:53:01 - file_reader - INFO - Processing file: core\treeSitter\treeSitterLanguage.py
2025-01-02 11:53:01 - file_reader - INFO - Successfully processed file: core\treeSitter\treeSitterLanguage.py
2025-01-02 11:53:01 - file_reader - INFO - Processing file: core\treeSitter\treeSitterParser.py
2025-01-02 11:53:03 - file_reader - ERROR - An exception occurred while processing core\treeSitter\treeSitterParser.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:53:03 - file_reader - INFO - Processing file: core\treeSitter\treeSitterQueryClasses.py
2025-01-02 11:53:03 - file_reader - ERROR - An exception occurred while processing core\treeSitter\treeSitterQueryClasses.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 11:56:09 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:56:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:56:11 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:59:32 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 11:59:32 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 11:59:35 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:00:08 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:00:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:00:11 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:01:33 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:01:33 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:01:36 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:02:23 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:02:23 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:02:26 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:29:06 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:29:06 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:29:08 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:31:17 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:31:17 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:31:20 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:31:36 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:31:36 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:31:38 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:32:23 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:32:23 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:32:25 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:40:44 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:40:44 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:40:46 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:44:22 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:44:22 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:44:25 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:46:14 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:46:14 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:46:17 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:48:16 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:48:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 12:48:16 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_2.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:48:16 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:48:18 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:50:09 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:50:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 12:50:09 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_2.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:50:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:50:12 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:53:03 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:53:03 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 12:53:03 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_2.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:53:03 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:53:05 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'NoneType' object has no attribute 'start_byte'
2025-01-02 12:55:18 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:55:18 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 12:55:18 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_2.py: type object 'tree_sitter.Tree' has no attribute 'from_bytes'
2025-01-02 12:55:18 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:55:18 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: type object 'tree_sitter.Tree' has no attribute 'from_bytes'
2025-01-02 12:58:43 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 12:58:43 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 12:58:43 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_2.py: type object 'tree_sitter.Tree' has no attribute 'from_bytes'
2025-01-02 12:58:43 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 12:58:43 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: type object 'tree_sitter.Tree' has no attribute 'from_bytes'
2025-01-02 13:16:09 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 13:16:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 13:16:09 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 13:16:09 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 13:16:11 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 13:17:13 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 13:17:13 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 13:17:13 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 13:17:13 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 13:17:15 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 13:18:18 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 13:18:18 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 13:18:18 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 13:18:18 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 13:18:20 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 13:22:28 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 13:22:28 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 13:22:28 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_2.py: 'tree_sitter.Tree' object has no attribute 'decode'
2025-01-02 13:22:28 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 13:22:31 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'tree_sitter.Tree' object has no attribute 'decode'
2025-01-02 13:25:56 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 13:25:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 13:25:56 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_2.py: 'tree_sitter.Tree' object has no attribute 'source'
2025-01-02 13:25:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 13:25:58 - file_reader - ERROR - An exception occurred while processing C:\Users\bornd\Desktop\New folder\test_file.py: 'tree_sitter.Tree' object has no attribute 'source'
2025-01-02 15:19:25 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:19:25 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:19:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:19:25 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:19:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:21:20 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:21:20 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:21:20 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:21:20 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:21:20 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:21:55 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:21:55 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:21:55 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:21:55 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:21:55 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:23:22 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:23:22 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:23:22 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:23:22 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:23:22 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:23:31 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:23:31 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:23:31 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:23:31 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:23:31 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:36:39 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:36:39 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:36:39 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:36:39 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:36:39 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:41:25 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:41:25 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:41:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:41:25 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:41:25 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:42:56 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:42:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:42:56 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:42:56 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:42:56 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:46:44 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:46:44 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:46:44 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:46:44 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:46:44 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:47:08 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 15:47:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:47:08 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 15:47:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 15:47:08 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 16:23:08 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 16:23:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 16:23:08 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 16:23:08 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 16:23:08 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 16:23:48 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 16:23:48 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 16:23:48 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 16:23:48 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 16:23:48 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 16:24:04 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 16:24:04 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 16:24:04 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 16:24:04 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 16:24:04 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 16:31:53 - file_reader - INFO - Processing directory: C:\Users\bornd\Desktop\New folder
2025-01-02 16:31:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 16:31:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_2.py
2025-01-02 16:31:53 - file_reader - INFO - Processing file: C:\Users\bornd\Desktop\New folder\test_file.py
2025-01-02 16:31:53 - file_reader - INFO - Successfully processed file: C:\Users\bornd\Desktop\New folder\test_file.py
